// <auto-generated />
using ConcesionarioAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcesionarioAPI.Migrations
{
    [DbContext(typeof(ConcesionarioContext))]
    [Migration("20260320150544_ActualizarCochesReales")]
    partial class ActualizarCochesReales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ConcesionarioAPI.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagenUrl = "/imagenes/a45.png",
                            Nombre = "Mercedes-Benz A45 AMG",
                            Stock = 3
                        },
                        new
                        {
                            Id = 2,
                            ImagenUrl = "/imagenes/c63.png",
                            Nombre = "Mercedes-Benz C63 AMG",
                            Stock = 2
                        },
                        new
                        {
                            Id = 3,
                            ImagenUrl = "/imagenes/cla45.png",
                            Nombre = "Mercedes-Benz CLA 45 AMG",
                            Stock = 4
                        },
                        new
                        {
                            Id = 4,
                            ImagenUrl = "/imagenes/cls63.png",
                            Nombre = "Mercedes-Benz CLS 63 AMG",
                            Stock = 1
                        },
                        new
                        {
                            Id = 5,
                            ImagenUrl = "/imagenes/g63.png",
                            Nombre = "Mercedes-Benz G63 AMG",
                            Stock = 2
                        },
                        new
                        {
                            Id = 6,
                            ImagenUrl = "/imagenes/gle63.png",
                            Nombre = "Mercedes-Benz GLE 63 AMG",
                            Stock = 3
                        },
                        new
                        {
                            Id = 7,
                            ImagenUrl = "/imagenes/gls.png",
                            Nombre = "Mercedes-Benz GLS",
                            Stock = 5
                        },
                        new
                        {
                            Id = 8,
                            ImagenUrl = "/imagenes/gt63.png",
                            Nombre = "Mercedes-AMG GT 63",
                            Stock = 1
                        },
                        new
                        {
                            Id = 9,
                            ImagenUrl = "/imagenes/maybach.png",
                            Nombre = "Mercedes-Maybach",
                            Stock = 1
                        },
                        new
                        {
                            Id = 10,
                            ImagenUrl = "/imagenes/sls.png",
                            Nombre = "Mercedes-Benz SLS AMG",
                            Stock = 1
                        },
                        new
                        {
                            Id = 11,
                            ImagenUrl = "/imagenes/alpinab7.png",
                            Nombre = "BMW Alpina B7",
                            Stock = 2
                        },
                        new
                        {
                            Id = 12,
                            ImagenUrl = "/imagenes/i8.png",
                            Nombre = "BMW i8",
                            Stock = 2
                        },
                        new
                        {
                            Id = 13,
                            ImagenUrl = "/imagenes/m2.png",
                            Nombre = "BMW M2",
                            Stock = 4
                        },
                        new
                        {
                            Id = 14,
                            ImagenUrl = "/imagenes/m3competitiontouring.png",
                            Nombre = "BMW M3 Competition Touring",
                            Stock = 3
                        },
                        new
                        {
                            Id = 15,
                            ImagenUrl = "/imagenes/m4competition.png",
                            Nombre = "BMW M4 Competition",
                            Stock = 3
                        },
                        new
                        {
                            Id = 16,
                            ImagenUrl = "/imagenes/m5cs.png",
                            Nombre = "BMW M5 CS",
                            Stock = 1
                        },
                        new
                        {
                            Id = 17,
                            ImagenUrl = "/imagenes/m8competition.png",
                            Nombre = "BMW M8 Competition",
                            Stock = 2
                        },
                        new
                        {
                            Id = 18,
                            ImagenUrl = "/imagenes/serie8convertible.png",
                            Nombre = "BMW Serie 8 Convertible",
                            Stock = 3
                        },
                        new
                        {
                            Id = 19,
                            ImagenUrl = "/imagenes/xm.png",
                            Nombre = "BMW XM",
                            Stock = 2
                        },
                        new
                        {
                            Id = 20,
                            ImagenUrl = "/imagenes/z4m40i.png",
                            Nombre = "BMW Z4 M40i",
                            Stock = 4
                        },
                        new
                        {
                            Id = 21,
                            ImagenUrl = "/imagenes/q8e-tron.png",
                            Nombre = "Audi Q8 e-tron",
                            Stock = 5
                        },
                        new
                        {
                            Id = 22,
                            ImagenUrl = "/imagenes/r8.png",
                            Nombre = "Audi R8",
                            Stock = 1
                        },
                        new
                        {
                            Id = 23,
                            ImagenUrl = "/imagenes/rs3.png",
                            Nombre = "Audi RS3",
                            Stock = 4
                        },
                        new
                        {
                            Id = 24,
                            ImagenUrl = "/imagenes/rs5coupe.png",
                            Nombre = "Audi RS5 Coupe",
                            Stock = 3
                        },
                        new
                        {
                            Id = 25,
                            ImagenUrl = "/imagenes/rs6.png",
                            Nombre = "Audi RS6 Avant",
                            Stock = 2
                        },
                        new
                        {
                            Id = 26,
                            ImagenUrl = "/imagenes/rs7.png",
                            Nombre = "Audi RS7",
                            Stock = 2
                        },
                        new
                        {
                            Id = 27,
                            ImagenUrl = "/imagenes/rse-trongt.png",
                            Nombre = "Audi RS e-tron GT",
                            Stock = 2
                        },
                        new
                        {
                            Id = 28,
                            ImagenUrl = "/imagenes/rsq8.png",
                            Nombre = "Audi RSQ8",
                            Stock = 3
                        },
                        new
                        {
                            Id = 29,
                            ImagenUrl = "/imagenes/s8.png",
                            Nombre = "Audi S8",
                            Stock = 2
                        },
                        new
                        {
                            Id = 30,
                            ImagenUrl = "/imagenes/ttrs.png",
                            Nombre = "Audi TT RS",
                            Stock = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
